config/routes.rb
Rails.application.routes.draw do

    get '/' => 'sessions#new'
    root :to => 'sessions#new'
    get '/signup' => 'users#new'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'

    resources :users
    resources :rooms
    resources :messages

end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :room, touch: true, autosave: true

  has_many :messages
  has_many :room_cards
  has_many :cards, through: :room_cards

  has_secure_password

  validates :email, presence: true, uniqueness: true
	validates :password, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action require_user: [:update]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url
      else
        redirect_to signup_path
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :first_name, :last_name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
  <div class="box" id="sign-up">
       <%= link_to "Back", login_path %>
    <div class="brand">
      <div class="logo">
      <div float: "left">
      <%= image_tag 'back_of_cards/b2fv.png', class:  "pure-img-responsive", width: '50' %> </div>

      </div>

      <h2 class="title">Sign up now</h2>
    </div>
<div id="form">
<% if !current_user %>
  <%= form_for @user do |f| %>
    Username  : <%= f.text_field     :user_name %><br>
    First name: <%= f.text_field     :first_name %><br>
    Last name : <%= f.text_field     :last_name %><br>
    Email     : <%= f.text_field     :email %><br>
    Password  : <%= f.password_field :password %><br><br>
    <%= f.submit "Submit", class: "button-link" %>
  <% end %>
<% else %>
  <% controller.redirect_to root_url %>
<% end %>
</div>
    </div>
  </div>
</div>

<style>

@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic);
html, body {
  font-family: "Open Sans", sans-serif;
  -webkit-font-smoothing: subpixel-antialiased;
}

.button-link {
    padding: 10px 15px;
    background: #44BA71;
    color: #FFF;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    border: solid 1px #208D4F;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.4);
    -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);
    -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);
    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);
    -webkit-transition-duration: 0.2s;
    -moz-transition-duration: 0.2s;
    transition-duration: 0.2s;
    -webkit-user-select:none;
    -moz-user-select:none;
    -ms-user-select:none;
    user-select:none;
}
.button-link:hover {
    background: #359483;
    border: solid 1px #2A7753;
    text-decoration: none;
}
.button-link:active {
    -webkit-box-shadow: inset 0 1px 4px rgba(0, 0, 0, 0.6);
    -moz-box-shadow: inset 0 1px 4px rgba(0, 0, 0, 0.6);
    box-shadow: inset 0 1px 4px rgba(0, 0, 0, 0.6);
    background: #2E8156;
    border: solid 1px #205F42;
}

#form {
  margin: 0 auto;
  width: 220px;
  clear: 100%;
}
#form input {
  width: 96%;
  clear: 100%;
  overflow: hidden;
}

#form input.button-link {
  width: 98.5%;
  clear: 100%;
  overflow: hidden;
}

.container {
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
  background: #2c3e50;
  background-size: cover;
}
.container .box#sign-up {
  box-sizing: border-box;
  width: 440px;
  margin: 40px auto;
  background: #FBFBFB;
  border-radius: 2px;
  box-shadow: 0 1px 20px 5px rgba(0, 0, 0, 0.4);
  padding: 15px 35px;
}
.container .box#sign-up .back {
  text-decoration: none;
  line-height: 40px;
}
.container .box#sign-up .back .back-arrow {
  color: #777;
}
.container .box#sign-up .brand .logo {
  position: relative;
  width: 65px;
  height: 60px;
  margin: 0 auto;
}
.container .box#sign-up .brand .logo .square {
  position: absolute;
  left: 9px;
  background: #FBFBFB;
  width: 40px;
  height: 40px;
  border: 3px solid #3498db;
  border-radius: 8px;
  transform: rotateX(55deg) rotateZ(45deg);
  box-shadow: 3px 3px 0px 2px white;
  -webkit-backface-visibility: hidden;
}
.container .box#sign-up .brand .logo .square:nth-of-type(1) {
  background: #3498db;
  top: 0;
  z-index: 99;
}
.container .box#sign-up .brand .logo .square:nth-of-type(2) {
  top: 12px;
  z-index: 98;
}
.container .box#sign-up .brand .logo .square:nth-of-type(3) {
  top: 24px;
  z-index: 97;
}
.container .box#sign-up .brand .title {
  font-weight: 400;
  color: #333;
  text-align: center;
}
.container .box#sign-up .form input {
  outline: 0;
  border: 1px solid #CCC;
  box-sizing: border-box;
  padding: 8px;
  color: #222;
  border-radius: 4px;
  width: 100%;
  margin: 5px 0;
  font-weight: 600;
}
.container .box#sign-up .form input::-webkit-input-placeholder {
  color: #AAA;
  font-weight: 400;
}
.container .box#sign-up .form .row input {
  width: calc(50% - 5px);
  float: left;
}
.container .box#sign-up .form .row input:first-of-type {
  margin-right: 10px;
}
.container .box#sign-up .form .checkbox {
  margin: 5px 0;
}
.container .box#sign-up .form .checkbox .checkbox-label {
  position: relative;
  display: table;
  width: 16px;
  height: 16px;
  background: white;
  border: 1px solid #CCC;
  border-radius: 2px;
  float: left;
  margin: 5px 5px 5px 0;
}
.container .box#sign-up .form .checkbox input[type="checkbox"] {
  display: none;
}
.container .box#sign-up .form .checkbox input[type="checkbox"]:checked ~ label.checkbox-label:before {
  content: "";
  position: absolute;
  top: 7px;
  left: 5px;
  height: 3px;
  width: 10px;
  background: #3498db;
  transform: rotate(-45deg);
}
.container .box#sign-up .form .checkbox input[type="checkbox"]:checked ~ label.checkbox-label:after {
  content: "";
  position: absolute;
  top: 5px;
  left: 3px;
  height: 6px;
  width: 3px;
  background: #3498db;
  transform: rotate(-45deg);
}
.container .box#sign-up .form .checkbox label.description {
  float: left;
  margin: 3px 0;
  color: #333;
}
.container .box#sign-up .form .checkbox label.description a {
  text-decoration: none;
  color: #5AA4EC;
  font-weight: 600;
}
.container .box#sign-up .form button {
  width: 100%;
  background: #3498db;
  line-height: 40px;
  border: 0;
  outline: 0;
  color: white;
  border-radius: 20px;
  font-weight: 300;
  margin-top: 15px;
  margin-bottom: 50px;
}
.pure-img-responsive{


}

</style>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">High Scores</div>
  <div class="panel-body">

    <div class="image-container">
      <%= image_tag 'back_of_cards/b2fv.png', class:  "pure-img-responsive-1" %>
      <%= image_tag 'back_of_cards/joker.png', class:  "pure-img-responsive-2"%>
    </div>

    <div class="panel-heading">See if you can beat your friends!</div>

  </div>

  <!-- Table -->
  <table class="table">
    <thead>
      <tr>
        <th>User name</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Wins</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.sort_by(&:wins).reverse.each do |user| %>
        <tr>
          <td><%= user.user_name %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
          <td><%= user.wins %></td>
          <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<style>
.panel-default {
  padding-top: 20px;
  margin-top: 20px;
  margin: 0 auto;
  width: 800px;
}
.panel-heading{
  text-align: center;
}

.image-container{
    text-align: center;
}



</style>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Total Wins:</strong>
  <%= @user.wins %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>