config/routes.rb
Rails.application.routes.draw do

    get '/' => 'sessions#new'
    root :to => 'sessions#new'
    get '/signup' => 'users#new'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'

    resources :users
    resources :rooms
    resources :messages

end

app/models/room.rb
class Room < ActiveRecord::Base

  belongs_to :room_type, touch: true
  has_many :messages
  has_many :users

  has_many :room_cards
  has_many :cards, through: :room_cards

  accepts_nested_attributes_for :users 
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
  has_many :rooms 
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action require_user: [:index, :new, :create, :show, :destroy]
  def index
    @rooms = Room.all
    @rooms.each do |room|
      room.destroy if room.users.length < 1
    end
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        current_user.update_columns(room_id: @room.id)
        Blackjack.create_deck(@room)

        format.html { redirect_to @room, notice: "Game Room created!" }
        format.json { render :show, location: @room }
      else
        format.html { render :new }
      end
    end
  end

  def show

    @room = Room.find(params[:id])

    @deck = @room.cards
    @hands = {}

    @hit = params[:hit]
    @stay = params[:stay]
    @restart = params[:restart]

    @ping = params[:ping]
    @disconnect = params[:disconnect]

    @current_user = current_user
    @room.users.each do |user|
      @current_user = user if current_user.id == user.id
    end

    if @room.users.length > 3
      current_user.update_columns(room_id: nil)
      @room.users.delete(current_user)
      redirect_to rooms_path, notice: "Sorry! Room is full!"
    else
      current_user.update_columns(room_id: @room.id)
    end

    if @ping == "true"

      if @room.users.length > 3
        current_user.update_columns(room_id: nil)
        @room.users.delete(current_user)
        redirect_to rooms_path, notice: "Sorry! Room is full!"
      else
        current_user.update_columns(room_id: @room.id)
      end

      if @disconnect == "true"
        Blackjack.user_quit(@room, current_user)
      else

        if @restart == "true"
          Blackjack.game_restart(@room)
          Blackjack.create_deck(@room)
          @room.users.each do |user|
            if user.cards.length < 2
              Blackjack.draw_card(@room, @deck, user, 2)
            end
          end
        end

        @room.users.each do |user|
          user.update_columns(dealer: false)
        end
        @room.users[-1].update_columns(dealer: true)
        current_user.update_columns(dealer: true) if @room.users[-1] == current_user

        if current_user.cards.length < 2
          Blackjack.draw_card(@room, @deck, current_user, 2)
        end

        if @hit == "true"
          Blackjack.draw_card(@room, @deck, current_user, 1)
        end

        if @stay == "true"
          current_user.update_columns(stay: true)
          @room.users.each do |user|
            user.update_columns(stay: true) if user == current_user
          end
        end

        @room.users.each do |user|
          @hands[user.id] = []
          user.cards.each do |card|
            @hands[user.id] << card
          end
        end

        @room.users.each do |user|
          Blackjack.calculate_hand(user)
          user.update_columns(bust: true) if Blackjack.player_bust?(user)
        end

        Blackjack.player_win?(@room)

        respond_to do |format|
          format.html
          format.js
          format.json {
            render json: {
              user: @current_user
            }
          }
        end
      end
      sleep 1
      PrivatePub.publish_to room_path, { users: @room.users, hands: @hands }
    end

  end

  def destroy
    @room = Room.find(params[:id])
    @room.users.each do |user|
      Blackjack.user_quit(@room, user)
    end
    @room.destroy
    redirect_to root_url
  end

  private
  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div id="container" align="center">
<% if current_user %>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">High Scores</div>
  <div class="panel-body">

    <div class="image-container">
      <%= image_tag 'back_of_cards/b2fv.png', class:  "pure-img-responsive-1" %>
      <%= image_tag 'back_of_cards/joker.png', class:  "pure-img-responsive-2"%>
    </div>

    <div class="panel-heading">Join a Game!</div>

  </div>
   <table class="table">
     <thead>
       <tr>
         <th>Room</th>
         <th colspan="3"></th>
       </tr>
     </thead>
     <tbody>
         <tr>
           <% @rooms.each do |room| %>
              <% if room.users.length < 4 && room.users.length > 0 %>
                <td><%= link_to "#{room.name}", room_path(room.id) %></td>
              <% end %>
           <% end %>
         </tr>
     </tbody>
   </table>
   <div>
     <%= link_to "Or make one!", new_room_path %>
   </div>
</div>
<% else %>
  <%= controller.redirect_to login_path %>
<% end %>
</div>

<style>
.panel-default {
  padding-top: 20px;
  margin-top: 20px;
  margin: 0 auto;
  width: 800px;
}
.panel-heading{
  text-align: center;
}

.image-container{
    text-align: center;
}
</style>

app/views/rooms/new.html.erb
<div id="container" align="center">
<% if current_user %>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Start Playing!</div>
  <div class="panel-body">

    <div class="image-container">
      <%= image_tag 'back_of_cards/b2fv.png', class:  "pure-img-responsive-1" %>
      <%= image_tag 'back_of_cards/joker.png', class:  "pure-img-responsive-2"%>
    </div>

    <div class="form">
    <%= form_for @room do |f| %>
      Game Room: <%= f.text_field :name %>
      <%= f.submit %>
    <% end %>
    </div>

</div>
<% else %>
  <%= controller.redirect_to login_path %>
<% end %>
</div>

<style>
.panel-default {
  padding-top: 20px;
  margin-top: 20px;
  margin: 0 auto;
  width: 800px;
}
.panel-heading{
  text-align: center;
}

.image-container{
    text-align: center;
}

.form
</style>

app/views/rooms/show.html.erb
<div id="game-container">

<h1><%= @room.name.capitalize %> Game</h1>

<div id="users">
</div>

<div id="chat-style">
</div>

<div id="messages">
  <h3>Chat!</h3>
</div>

<%= form_for Message.new, remote: true do |f| %>
  <h4>Chat! :)</h4>
  <div id="new_message_text">
    <%= f.text_field :content %><br>
  </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :room_id, value: current_user.room.id %>
  <div class="actions">
    <%= f.submit "Send" %>
  </div>
<% end %>

<div id="notice">
</div>



<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <div id="buttons">
    </div>
  </div>
</nav>


</div>

<%= subscribe_to room_path %>

<style>

  #buttons {
    display: flex;
    flex-direction: row;
    justify-content: center;
  }

  #buttons div {
    margin: 5px;
    padding: 5px;
  }

  #users {
    max-width: 500px;
  }
  #game-container {
    /*background: #E84F75 no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;*/
    padding: 40px;
    color: white;
    margin-bottom: 0;
  }

  #game-container h1 {
    text-align: center;
    background-color: rgba(45, 99, 214, 0.2);
    padding: 20px;
    border-radius: 5px;
    color: white;
  }

  #messages{
    position: fixed;
    right: 1em;
    top: 8em;
    word-wrap: break-word;
    width: 200px;
    border-style: none;
    border-radius: 10px;
    background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAaUlEQVQIW2MUSHP/z/ztEMNfLg+GPx+3MAjwczMwypaK/n//6AOYAwIvXn5nYGTxZ//PoCjFwPH8CcOPH0wMIDYjTzjr/x+SMgw839QYvnDdAtOMAmmB/5m/7WD4+Pkfg7CaGcPPj1wMAFY6I/ye5jZdAAAAAElFTkSuQmCC);
    height: 300px;
    overflow-y: auto;
  }

  .new_message{
    padding: 10px;
    position: fixed;
    right: 2em;
    bottom: 5em;
    text-align: center;
    border-style: none;
    border-radius: 10px;
    background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAaUlEQVQIW2MUSHP/z/ztEMNfLg+GPx+3MAjwczMwypaK/n//6AOYAwIvXn5nYGTxZ//PoCjFwPH8CcOPH0wMIDYjTzjr/x+SMgw839QYvnDdAtOMAmmB/5m/7WD4+Pkfg7CaGcPPj1wMAFY6I/ye5jZdAAAAAElFTkSuQmCC);
  }

  .new_message input{
    color: black;
  }

  #messages h3{
    padding: 10px;
    text-align: center;
    color: white;
  }

  #messages li{
    margin-bottom: 5px;
    padding: 10px;
    border-style: none;
    border-radius: 10px;
    background: white;
    color: black;
  }

  #chat-style{
    position: fixed;
    width: 226px;
    height: 800px;
    top: 0.1em;
    right: 0.1em;
    background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAaUlEQVQIW2MUSHP/z/ztEMNfLg+GPx+3MAjwczMwypaK/n//6AOYAwIvXn5nYGTxZ//PoCjFwPH8CcOPH0wMIDYjTzjr/x+SMgw839QYvnDdAtOMAmmB/5m/7WD4+Pkfg7CaGcPPj1wMAFY6I/ye5jZdAAAAAElFTkSuQmCC);
    margin-bottom: 0;
  }

  #buttons{
    color: black;
  }
</style>

<script>

  $(function(){

    $.ajax({
      url: "<%= room_path %>",
      dataType: "json",
      type: "GET",
      data: { ping: "true" },

      }).done(function(data){
        $("#buttons").html('');
        if (data.user.stay == false && data.user.bust == false && data.user.win == false){
          $("#buttons").append("<button type='button' id='hit'>HIT</button><button type='button' id='stay'>STAY</button>");
        }
        $("#buttons").append("<div id='gameover'><button type='button' id='restart'>RESTART</button></div>");
        $("#" + data.user.user_name).append("<h4>You are here!</h4>");
      });

    $("#buttons").on("click", "#hit", function(){
      $.ajax({
        url: "<%= room_path %>",
        dataType: "json",
        type: "GET",
        data: { ping: "true", hit: "true"}
      }).done(function(data){
        $("#buttons").html('');
        if (data.user.stay == false && data.user.bust == false && data.user.win == false){
          $("#buttons").append("<button type='button' id='hit'>HIT</button><button type='button' id='stay'>STAY</button>");
        }
        $("#buttons").append("<div id='gameover'><button type='button' id='restart'>RESTART</button></div>");
        $("#" + data.user.user_name).append("<h4>You are here!</h4>");
      });
    });

    $("#buttons").on("click", "#stay", function(){
      $.ajax({
        url: "<%= room_path %>",
        dataType: "json",
        type: "GET",
        data: { ping: "true", stay: "true"}
      }).done(function(data){
        $("#buttons").html('');
        if (data.user.stay == false && data.user.bust == false && data.user.win == false){
          $("#buttons").append("<button type='button' id='hit'>HIT</button><button type='button' id='stay'>STAY</button>");
        }
        $("#buttons").append("<div id='gameover'><button type='button' id='restart'>RESTART</button></div>");
        $("#" + data.user.user_name).append("<h4>You are here!</h4>");
      });
    });

    $("#buttons").on("click", "#restart", function(){
      $.ajax({
        url: "<%= room_path %>",
        dataType: "json",
        type: "GET",
        data: { ping: "true", restart: "true"}
      }).done(function(data){
        $("#buttons").html('');
        if (data.user.stay == false && data.user.bust == false && data.user.win == false){
          $("#buttons").append("<button type='button' id='hit'>HIT</button><button type='button' id='stay'>STAY</button>");
        }
        $("#buttons").append("<div id='gameover'><button type='button' id='restart'>RESTART</button></div>");
        $("#" + data.user.user_name).append("<h4>You are here!</h4>");
      });
    });

    PrivatePub.subscribe("<%= room_path %>", function(data, channel) {

      if (data.message != null){
        $("#messages").append("<li>" + data.user.user_name + ": " + data.message.content + "</li>");
        $("#message_content").val('');
      }

      if (data.message == null){
        $("#notice").html('');
        if ($("#gameinsession").length < 1){
          $("#notice").append("<p id='gameinsession'>Notice: Game is currently in session. Dealer should restart the game if new players join in!</p>");
        }
        $("#users").html('');
        $("#pleaserestart").html('');
        $.each(data, function(index, users){
          $.each(users, function(u, user){
            if (user.user_name != undefined){
              debugger;
              if ($("#" + user.user_name).length < 1) {

                $("#users").append("<div id='" + user.user_name + "'><div><h4>" + user.user_name + " is playing!" + "</h4></div></div>");

                $("#" + user.user_name).append("<div>" + user.score + " in hand!</div>");

                debugger;

                if (user.win == true){
                  $("#notice").append("<p id='pleaserestart'>The game is now over. You should restart!</p>");
                  $("#" + user.user_name).append("<div>" + user.user_name + " has won the game!</div>");
                }

                if (user.bust == true){
                  $("#" + user.user_name).append("<div>" + user.user_name + "\'s hand is a bust!</div>");
                }

                $.each(data.hands, function(h_id, hand){
                  if (h_id == user.id){
                    $.each(hand, function(c, card){
                      $("#" + user.user_name).append("<div id='" + user.user_name + "_cards'></div>");
                      $("#" + user.user_name + "_cards").append("<img src='/images/" + card.image + "'>");
                      $("#" + user.user_name + "_cards").css({"text-align": "center"});
                      $("#" + user.user_name).css({"width": "300px"});
                      $("#" + user.user_name).css({"text-align": "center"});
                      $("#users").css({"display": "flex"})
                      $("#users").css({"flex-direction": "row"})
                      $("#users").css({"margin-top": "40px"});
                    });
                  }
                });

                if (user.dealer == true){
                  $("#" + user.user_name).append("<div><h2>Dealer</h2></div>");
                }
              }
            }
          });
        });
      };
    });

    $(window).bind('beforeunload', function(){
      $.ajax({
        url: "<%= room_path %>",
        type: "GET",
        data: { ping: "true", disconnect: "true" },
        async: false
      }).done(function(){
      });
    });
  });

</script>